import React from 'react';

import './App.css';
import Header from './layout/header/Header';
import Sidebar from './layout/sidebar/Sidebar';
import Board from './layout/board/Board';

function App() {
  return (
    <div className="w-full h-full relative">
      <Header />
      <Sidebar />
      <Board>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Accumsan sit amet nulla facilisi. Aenean pharetra magna ac placerat vestibulum lectus. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Sed ullamcorper morbi tincidunt ornare. Vel pretium lectus quam id leo in vitae turpis massa. Pharetra convallis posuere morbi leo urna molestie. Viverra justo nec ultrices dui sapien. Varius vel pharetra vel turpis nunc eget lorem dolor.

          Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Morbi tincidunt ornare massa eget. Aliquam vestibulum morbi blandit cursus. Enim ut sem viverra aliquet eget sit. Non odio euismod lacinia at quis. Facilisis volutpat est velit egestas dui id ornare arcu odio. Sollicitudin ac orci phasellus egestas. A condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Volutpat consequat mauris nunc congue. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Diam sollicitudin tempor id eu nisl nunc mi. Arcu cursus euismod quis viverra nibh cras pulvinar mattis nunc. Enim blandit volutpat maecenas volutpat blandit aliquam etiam.

          Mauris nunc congue nisi vitae. Eget magna fermentum iaculis eu non diam phasellus vestibulum. In hendrerit gravida rutrum quisque. Vitae suscipit tellus mauris a diam maecenas sed. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Sit amet nulla facilisi morbi tempus iaculis urna id. Odio facilisis mauris sit amet. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse. Duis convallis convallis tellus id interdum velit laoreet id donec. Turpis cursus in hac habitasse. Sit amet consectetur adipiscing elit. Consequat mauris nunc congue nisi vitae suscipit tellus. Ut porttitor leo a diam sollicitudin tempor id eu. Hendrerit dolor magna eget est lorem ipsum dolor sit.

          Purus sit amet luctus venenatis lectus magna. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Fermentum odio eu feugiat pretium nibh ipsum consequat. Vitae turpis massa sed elementum tempus egestas sed. Vitae purus faucibus ornare suspendisse sed. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Tristique senectus et netus et malesuada fames ac turpis. Elit duis tristique sollicitudin nibh sit amet. Metus aliquam eleifend mi in. Quis lectus nulla at volutpat.

          At urna condimentum mattis pellentesque id nibh tortor id aliquet. Curabitur vitae nunc sed velit. A erat nam at lectus urna duis. Gravida in fermentum et sollicitudin. Diam quam nulla porttitor massa. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Enim ut tellus elementum sagittis vitae et leo. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Enim neque volutpat ac tincidunt vitae semper. Suspendisse ultrices gravida dictum fusce ut. Dolor sed viverra ipsum nunc aliquet bibendum. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Tellus mauris a diam maecenas. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec.

          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Accumsan sit amet nulla facilisi. Aenean pharetra magna ac placerat vestibulum lectus. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Sed ullamcorper morbi tincidunt ornare. Vel pretium lectus quam id leo in vitae turpis massa. Pharetra convallis posuere morbi leo urna molestie. Viverra justo nec ultrices dui sapien. Varius vel pharetra vel turpis nunc eget lorem dolor.

          Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Morbi tincidunt ornare massa eget. Aliquam vestibulum morbi blandit cursus. Enim ut sem viverra aliquet eget sit. Non odio euismod lacinia at quis. Facilisis volutpat est velit egestas dui id ornare arcu odio. Sollicitudin ac orci phasellus egestas. A condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Volutpat consequat mauris nunc congue. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Diam sollicitudin tempor id eu nisl nunc mi. Arcu cursus euismod quis viverra nibh cras pulvinar mattis nunc. Enim blandit volutpat maecenas volutpat blandit aliquam etiam.

          Mauris nunc congue nisi vitae. Eget magna fermentum iaculis eu non diam phasellus vestibulum. In hendrerit gravida rutrum quisque. Vitae suscipit tellus mauris a diam maecenas sed. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Sit amet nulla facilisi morbi tempus iaculis urna id. Odio facilisis mauris sit amet. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse. Duis convallis convallis tellus id interdum velit laoreet id donec. Turpis cursus in hac habitasse. Sit amet consectetur adipiscing elit. Consequat mauris nunc congue nisi vitae suscipit tellus. Ut porttitor leo a diam sollicitudin tempor id eu. Hendrerit dolor magna eget est lorem ipsum dolor sit.

          Purus sit amet luctus venenatis lectus magna. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Fermentum odio eu feugiat pretium nibh ipsum consequat. Vitae turpis massa sed elementum tempus egestas sed. Vitae purus faucibus ornare suspendisse sed. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Tristique senectus et netus et malesuada fames ac turpis. Elit duis tristique sollicitudin nibh sit amet. Metus aliquam eleifend mi in. Quis lectus nulla at volutpat.

          At urna condimentum mattis pellentesque id nibh tortor id aliquet. Curabitur vitae nunc sed velit. A erat nam at lectus urna duis. Gravida in fermentum et sollicitudin. Diam quam nulla porttitor massa. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Enim ut tellus elementum sagittis vitae et leo. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Enim neque volutpat ac tincidunt vitae semper. Suspendisse ultrices gravida dictum fusce ut. Dolor sed viverra ipsum nunc aliquet bibendum. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Tellus mauris a diam maecenas. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec.

          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Accumsan sit amet nulla facilisi. Aenean pharetra magna ac placerat vestibulum lectus. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Sed ullamcorper morbi tincidunt ornare. Vel pretium lectus quam id leo in vitae turpis massa. Pharetra convallis posuere morbi leo urna molestie. Viverra justo nec ultrices dui sapien. Varius vel pharetra vel turpis nunc eget lorem dolor.

          Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Morbi tincidunt ornare massa eget. Aliquam vestibulum morbi blandit cursus. Enim ut sem viverra aliquet eget sit. Non odio euismod lacinia at quis. Facilisis volutpat est velit egestas dui id ornare arcu odio. Sollicitudin ac orci phasellus egestas. A condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Volutpat consequat mauris nunc congue. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Diam sollicitudin tempor id eu nisl nunc mi. Arcu cursus euismod quis viverra nibh cras pulvinar mattis nunc. Enim blandit volutpat maecenas volutpat blandit aliquam etiam.

          Mauris nunc congue nisi vitae. Eget magna fermentum iaculis eu non diam phasellus vestibulum. In hendrerit gravida rutrum quisque. Vitae suscipit tellus mauris a diam maecenas sed. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Sit amet nulla facilisi morbi tempus iaculis urna id. Odio facilisis mauris sit amet. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse. Duis convallis convallis tellus id interdum velit laoreet id donec. Turpis cursus in hac habitasse. Sit amet consectetur adipiscing elit. Consequat mauris nunc congue nisi vitae suscipit tellus. Ut porttitor leo a diam sollicitudin tempor id eu. Hendrerit dolor magna eget est lorem ipsum dolor sit.

          Purus sit amet luctus venenatis lectus magna. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Fermentum odio eu feugiat pretium nibh ipsum consequat. Vitae turpis massa sed elementum tempus egestas sed. Vitae purus faucibus ornare suspendisse sed. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Tristique senectus et netus et malesuada fames ac turpis. Elit duis tristique sollicitudin nibh sit amet. Metus aliquam eleifend mi in. Quis lectus nulla at volutpat.

          At urna condimentum mattis pellentesque id nibh tortor id aliquet. Curabitur vitae nunc sed velit. A erat nam at lectus urna duis. Gravida in fermentum et sollicitudin. Diam quam nulla porttitor massa. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Enim ut tellus elementum sagittis vitae et leo. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Enim neque volutpat ac tincidunt vitae semper. Suspendisse ultrices gravida dictum fusce ut. Dolor sed viverra ipsum nunc aliquet bibendum. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Tellus mauris a diam maecenas. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec.

          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Accumsan sit amet nulla facilisi. Aenean pharetra magna ac placerat vestibulum lectus. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Sed ullamcorper morbi tincidunt ornare. Vel pretium lectus quam id leo in vitae turpis massa. Pharetra convallis posuere morbi leo urna molestie. Viverra justo nec ultrices dui sapien. Varius vel pharetra vel turpis nunc eget lorem dolor.

          Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Morbi tincidunt ornare massa eget. Aliquam vestibulum morbi blandit cursus. Enim ut sem viverra aliquet eget sit. Non odio euismod lacinia at quis. Facilisis volutpat est velit egestas dui id ornare arcu odio. Sollicitudin ac orci phasellus egestas. A condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Volutpat consequat mauris nunc congue. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Diam sollicitudin tempor id eu nisl nunc mi. Arcu cursus euismod quis viverra nibh cras pulvinar mattis nunc. Enim blandit volutpat maecenas volutpat blandit aliquam etiam.

          Mauris nunc congue nisi vitae. Eget magna fermentum iaculis eu non diam phasellus vestibulum. In hendrerit gravida rutrum quisque. Vitae suscipit tellus mauris a diam maecenas sed. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Sit amet nulla facilisi morbi tempus iaculis urna id. Odio facilisis mauris sit amet. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse. Duis convallis convallis tellus id interdum velit laoreet id donec. Turpis cursus in hac habitasse. Sit amet consectetur adipiscing elit. Consequat mauris nunc congue nisi vitae suscipit tellus. Ut porttitor leo a diam sollicitudin tempor id eu. Hendrerit dolor magna eget est lorem ipsum dolor sit.

          Purus sit amet luctus venenatis lectus magna. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Fermentum odio eu feugiat pretium nibh ipsum consequat. Vitae turpis massa sed elementum tempus egestas sed. Vitae purus faucibus ornare suspendisse sed. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Tristique senectus et netus et malesuada fames ac turpis. Elit duis tristique sollicitudin nibh sit amet. Metus aliquam eleifend mi in. Quis lectus nulla at volutpat.

          At urna condimentum mattis pellentesque id nibh tortor id aliquet. Curabitur vitae nunc sed velit. A erat nam at lectus urna duis. Gravida in fermentum et sollicitudin. Diam quam nulla porttitor massa. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Enim ut tellus elementum sagittis vitae et leo. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Enim neque volutpat ac tincidunt vitae semper. Suspendisse ultrices gravida dictum fusce ut. Dolor sed viverra ipsum nunc aliquet bibendum. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Tellus mauris a diam maecenas. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec.
        </p>
      </Board>
    </div>
  );
}

export default App;
